import {
  Battery,
  Disc3,
  Droplets,
  Fuel,
  HelpCircle,
  Settings,
  Truck,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type ServiceTarget = "xe-may" | "o-to";

export interface ResQService {
  id: string;
  title: string;
  titleEn: string;
  desc: string;
  descEn: string;
  price: string;
  eta: string;
  icon: LucideIcon;
  types: ServiceTarget[];
  includes?: string[];
  includesEn?: string[];
}

export const resqServices: ResQService[] = [
  {
    id: "va-lop",
    title: "Vá lốp / Thay lốp",
    titleEn: "Tire repair / replacement",
    desc: "Xử lý nhanh lốp xe bị thủng, xẹp hoặc hư hỏng trên đường.",
    descEn: "Fast roadside help for punctured, flat, or damaged tires.",
    price: "Từ 50.000đ",
    eta: "15-25 phút",
    icon: Wrench,
    types: ["xe-may", "o-to"],
    includes: ["Kiểm tra tình trạng lốp", "Vá hoặc thay lốp mới", "Bơm hơi đúng áp suất"],
    includesEn: ["Inspect the tire condition", "Patch or replace the tire", "Inflate to the right pressure"],
  },
  {
    id: "ac-quy",
    title: "Kích bình / Thay ắc quy",
    titleEn: "Battery jumpstart / replacement",
    desc: "Kích nổ hoặc thay ắc quy mới ngay tại chỗ.",
    descEn: "Jumpstart the vehicle or replace the battery on site.",
    price: "Từ 100.000đ",
    eta: "15-25 phút",
    icon: Battery,
    types: ["xe-may", "o-to"],
    includes: ["Kiểm tra ắc quy", "Kích bình hoặc thay mới", "Test hệ thống sạc"],
    includesEn: ["Check the battery", "Jumpstart or replace it", "Test the charging system"],
  },
  {
    id: "nhien-lieu",
    title: "Tiếp nhiên liệu (Xăng/Dầu)",
    titleEn: "Fuel delivery",
    desc: "Giao xăng hoặc dầu diesel đến vị trí của bạn.",
    descEn: "Deliver petrol or diesel directly to your location.",
    price: "Từ 80.000đ",
    eta: "15-30 phút",
    icon: Fuel,
    types: ["xe-may", "o-to"],
    includes: ["Giao xăng/dầu tận nơi", "Đổ nhiên liệu an toàn", "Kiểm tra hệ thống nhiên liệu"],
    includesEn: ["Deliver fuel roadside", "Refuel safely", "Check the fuel system"],
  },
  {
    id: "dong-co",
    title: "Sự cố động cơ",
    titleEn: "Engine issue",
    desc: "Kiểm tra và xử lý các sự cố động cơ tại hiện trường.",
    descEn: "Diagnose and handle engine issues on site.",
    price: "Từ 200.000đ",
    eta: "20-30 phút",
    icon: Settings,
    types: ["xe-may", "o-to"],
    includes: ["Chẩn đoán lỗi động cơ", "Sửa chữa tại chỗ", "Tư vấn bảo dưỡng"],
    includesEn: ["Diagnose the engine", "On-site repair", "Maintenance advice"],
  },
  {
    id: "dien",
    title: "Sự cố điện",
    titleEn: "Electrical issue",
    desc: "Khắc phục lỗi hệ thống điện, đèn, còi xe.",
    descEn: "Fix lighting, horn, or electrical system faults.",
    price: "Từ 150.000đ",
    eta: "15-25 phút",
    icon: Zap,
    types: ["xe-may", "o-to"],
    includes: ["Kiểm tra hệ thống điện", "Sửa lỗi đèn, còi", "Thay cầu chì, rơ le"],
    includesEn: ["Inspect the electrical system", "Fix lights and horn issues", "Replace fuse or relay"],
  },
  {
    id: "phanh",
    title: "Phanh / Thắng",
    titleEn: "Brake system",
    desc: "Kiểm tra và sửa chữa hệ thống phanh.",
    descEn: "Inspect and repair the braking system.",
    price: "Từ 120.000đ",
    eta: "20-30 phút",
    icon: Disc3,
    types: ["xe-may", "o-to"],
    includes: ["Kiểm tra má phanh", "Thay má phanh", "Xả gió phanh"],
    includesEn: ["Inspect brake pads", "Replace brake pads", "Bleed the brake line"],
  },
  {
    id: "dau",
    title: "Thay dầu",
    titleEn: "Oil change",
    desc: "Dịch vụ thay dầu nhớt tại nhà hoặc tại chỗ.",
    descEn: "Roadside or at-home engine oil service.",
    price: "Từ 100.000đ",
    eta: "15-20 phút",
    icon: Droplets,
    types: ["xe-may", "o-to"],
    includes: ["Xả dầu cũ", "Thay dầu mới chính hãng", "Kiểm tra lọc dầu"],
    includesEn: ["Drain old oil", "Refill with approved oil", "Check the oil filter"],
  },
  {
    id: "cuu-ho",
    title: "Cứu hộ / Kéo xe",
    titleEn: "Towing / recovery",
    desc: "Xe cứu hộ đến kéo xe về garage an toàn.",
    descEn: "Recovery truck arrives to tow the vehicle safely.",
    price: "Từ 300.000đ",
    eta: "15-30 phút",
    icon: Truck,
    types: ["xe-may", "o-to"],
    includes: ["Kéo xe về garage", "Bảo hiểm khi vận chuyển", "Tư vấn garage uy tín"],
    includesEn: ["Tow the vehicle", "Protected transport", "Trusted garage recommendation"],
  },
  {
    id: "bugi",
    title: "Thay bugi",
    titleEn: "Spark plug replacement",
    desc: "Kiểm tra và thay bugi cho xe máy tại chỗ.",
    descEn: "Inspect and replace motorbike spark plugs on site.",
    price: "Từ 40.000đ",
    eta: "10-15 phút",
    icon: Wrench,
    types: ["xe-may"],
    includes: ["Kiểm tra bugi cũ", "Thay bugi mới", "Điều chỉnh khe hở"],
    includesEn: ["Inspect the old spark plug", "Install a new one", "Adjust the gap"],
  },
  {
    id: "nhong-sen",
    title: "Thay nhông sên dĩa",
    titleEn: "Chain and sprocket set",
    desc: "Thay bộ nhông sên dĩa cho xe máy tận nơi.",
    descEn: "Replace the motorbike chain and sprocket set on site.",
    price: "Từ 250.000đ",
    eta: "30-45 phút",
    icon: Settings,
    types: ["xe-may"],
    includes: ["Tháo bộ cũ", "Lắp nhông sên dĩa mới", "Căn chỉnh sên"],
    includesEn: ["Remove the old set", "Install the new kit", "Adjust the chain tension"],
  },
  {
    id: "dieu-hoa",
    title: "Điều hòa / Máy lạnh ô tô",
    titleEn: "Car AC support",
    desc: "Kiểm tra, bơm gas và sửa chữa hệ thống điều hòa.",
    descEn: "Check, refill, and repair the air-conditioning system.",
    price: "Từ 300.000đ",
    eta: "30-45 phút",
    icon: Droplets,
    types: ["o-to"],
    includes: ["Kiểm tra gas lạnh", "Bơm gas điều hòa", "Vệ sinh dàn lạnh"],
    includesEn: ["Check coolant gas", "Refill the AC", "Clean the evaporator"],
  },
  {
    id: "mo-khoa",
    title: "Mở khóa ô tô",
    titleEn: "Car unlock",
    desc: "Mở khóa xe khi bị nhốt chìa bên trong hoặc mất chìa.",
    descEn: "Unlock the vehicle when the key is trapped inside or missing.",
    price: "Từ 400.000đ",
    eta: "20-30 phút",
    icon: HelpCircle,
    types: ["o-to"],
    includes: ["Mở khóa chuyên nghiệp", "Không làm hỏng khóa", "Làm chìa dự phòng"],
    includesEn: ["Professional unlock service", "No lock damage", "Backup key support"],
  },
  {
    id: "chung",
    title: "Hỗ trợ chung",
    titleEn: "General support",
    desc: "Bất kỳ sự cố nào khác trên đường.",
    descEn: "For any other roadside issue that does not fit a preset service.",
    price: "Liên hệ",
    eta: "15-30 phút",
    icon: HelpCircle,
    types: ["xe-may", "o-to"],
    includes: ["Đánh giá tình trạng", "Xử lý tại chỗ", "Tư vấn giải pháp"],
    includesEn: ["Assess the situation", "On-site assistance", "Recommend the right next step"],
  },
];

export const resqServiceFilters = [
  { label: "Tất cả", labelEn: "All", value: "all" },
  { label: "Xe máy", labelEn: "Motorbike", value: "xe-may" },
  { label: "Ô tô", labelEn: "Car", value: "o-to" },
] as const;
